"""add_segments_jsonb

Revision ID: 9d9ca94f6ff5
Revises: 9b05db18920d
Create Date: 2026-07-06 11:48:07.653960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d9ca94f6ff5'
down_revision: Union[str, Sequence[str], None] = '9b05db18920d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'segments')
    # ### end Alembic commands ###
